name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production

jobs:
  deploy-to-production:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    
    - name: Create environment files
      run: |
        echo "${{ secrets.FIREBASE_CONFIG_PRODUCTION }}" > ./db-master/.env
        echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_PRODUCTION }}" > ./service-account.json
    
    - name: Install main dependencies
      working-directory: ./db-master
      run: npm ci
    
    - name: Install function dependencies
      working-directory: ./functions
      run: npm ci
    
    - name: Build frontend for production
      working-directory: ./db-master
      run: |
        npm run build
      env:
        VITE_APP_ENV: production
        VITE_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY_PRODUCTION }}
        VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN_PRODUCTION }}
        VITE_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID_PRODUCTION }}
        VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET_PRODUCTION }}
        VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID_PRODUCTION }}
        VITE_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID_PRODUCTION }}
    
    - name: Build functions
      working-directory: ./functions
      run: npm run build
    
    - name: Deploy to Firebase Production
      id: firebase_deploy
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PRODUCTION }}'
        projectId: db888-67827
        channelId: live
        target: production
      env:
        FIREBASE_CLI_PREVIEWS: hostingchannels
    
    - name: Deploy Firebase Functions to Production
      id: functions_deploy
      run: |
        npm install -g firebase-tools
        FUNCTIONS_OUTPUT=$(firebase deploy --only functions --project db888-67827 --force --token "${{ secrets.FIREBASE_TOKEN }}" --non-interactive)
        echo "::set-output name=functions_output::$FUNCTIONS_OUTPUT"
        echo "$FUNCTIONS_OUTPUT" | grep -oP 'Function URL \(.*\): \K.*' | head -1 > functions_url.txt
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ./service-account.json
    
    - name: Log Deployment
      run: |
        mkdir -p deployment-logs
        node scripts/deployment/log-deployment.js production ${{ steps.firebase_deploy.outputs.hosting_url }} ${{ steps.functions_deploy.outputs.functions_url }}
    
    - name: Create Release Tag
      id: create_tag
      run: |
        VERSION=$(date +'v%Y.%m.%d-%H%M')
        echo "::set-output name=version::$VERSION"
        git tag $VERSION
        git push origin $VERSION
    
    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.create_tag.outputs.version }}
        release_name: Release ${{ steps.create_tag.outputs.version }}
        draft: false
        prerelease: false
        body: |
          Production Release ${{ steps.create_tag.outputs.version }}
          
          Deployed to https://db888-67827.web.app
    
    - name: Notify deployment success
      run: |
        echo "Deployed successfully to production environment"
        echo "Visit https://db888-67827.web.app to view the application"